# Generated by Django 4.2.7 on 2023-11-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sensor_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmer',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
